![image.png](attachment:image.png)

![image.png](attachment:image.png)

Este es un ejercicio extra por si quieres practicar más el filtrado de dataframes, en algunos apartados tendrás que recordar métodos empleados en ejercicios de la unidad anterior.
A por ello

# Fictional Army - Filtrado y ordenado

In [1]:
import pandas as pd

### Paso 2. Estos son los datos dados en forma de diccionario

In [3]:
# Create an example dataframe about a fictional army
raw_data = {'regiment': ['Nighthawks', 'Nighthawks', 'Nighthawks', 'Nighthawks', 'Dragoons', 'Dragoons', 'Dragoons', 'Dragoons', 'Scouts', 'Scouts', 'Scouts', 'Scouts'],
            'company': ['1st', '1st', '2nd', '2nd', '1st', '1st', '2nd', '2nd','1st', '1st', '2nd', '2nd'],
            'deaths': [523, 52, 25, 616, 43, 234, 523, 62, 62, 73, 37, 35],
            'battles': [5, 42, 2, 2, 4, 7, 8, 3, 4, 7, 8, 9],
            'size': [1045, 957, 1099, 1400, 1592, 1006, 987, 849, 973, 1005, 1099, 1523],
            'veterans': [1, 5, 62, 26, 73, 37, 949, 48, 48, 435, 63, 345],
            'readiness': [1, 2, 3, 3, 2, 1, 2, 3, 2, 1, 2, 3],
            'armored': [1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1],
            'deserters': [4, 24, 31, 2, 3, 4, 24, 31, 2, 3, 2, 3],
            'origin': ['Arizona', 'California', 'Texas', 'Florida', 'Maine', 'Iowa', 'Alaska', 'Washington', 'Oregon', 'Wyoming', 'Louisana', 'Georgia']}

### Paso 3. Crear un dataframe y asignarlo a una variable llamada ejército.

In [4]:
ejercito = pd.DataFrame(raw_data)
ejercito.head(20)

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,Dragoons,1st,43,4,1592,73,2,0,3,Maine
5,Dragoons,1st,234,7,1006,37,1,1,4,Iowa
6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,Dragoons,2nd,62,3,849,48,3,1,31,Washington
8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming
10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

### Paso 4. Pon la columna "origin" como índice del marco de datos

In [6]:
ejercito.set_index('origin', inplace=True)
ejercito.head(20)

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Paso 5. Imprima sólo los veteranos de la columna

In [9]:
ejercito['veterans']

origin
Arizona         1
California      5
Texas          62
Florida        26
Maine          73
Iowa           37
Alaska        949
Washington     48
Oregon         48
Wyoming       435
Louisana       63
Georgia       345
Name: veterans, dtype: int64

### Paso 6. Imprime las columnas "veterans" y "deaths"

In [10]:
ejercito[['veterans', 'deaths']]

            veterans  deaths
origin
Arizona            1     523
California         5      52
Texas             62      25
Florida           26     616
Maine             73      43
Iowa              37     234
Alaska           949     523
Washington        48      62
Oregon            48      62
Wyoming          435      73
Louisana          63      37
Georgia          345      35

### Paso 7. Imprime el nombre de todas las columnas.

In [11]:
ejercito.columns

Index(['regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters'],
      dtype='object')

### Paso 8. Seleccione las columnas "deaths", "size" y "deserters" de Maine y Alaska

In [12]:
ejercito.loc[['Maine', 'Alaska'], ['deaths', 'deserters']]

        deaths  deserters
origin
Maine       43          3
Alaska     523         24

### Paso 9. Selecciona las filas 3 a 7 y las columnas 3 a 6

In [13]:
ejercito.iloc[2:7, 2:6]

         deaths  battles  size  veterans
origin
Texas        25        2  1099        62
Florida     616        2  1400        26
Maine        43        4  1592        73
Iowa        234        7  1006        37
Alaska      523        8   987       949

### Paso 10. Selecciona todas las filas después de la cuarta fila y todas las columnas

In [15]:
ejercito.iloc[3:, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Paso 11. Selecciona todas las filas hasta la 4ª fila y todas las columnas

In [16]:
ejercito.iloc[:4, :]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2

### Paso 12. Seleccione la 3ª columna hasta la 7ª columna

In [17]:
ejercito.iloc[:, 2:7]

            deaths  battles  size  veterans  readiness
origin
Arizona        523        5  1045         1          1
California      52       42   957         5          2
Texas           25        2  1099        62          3
Florida        616        2  1400        26          3
Maine           43        4  1592        73          2
Iowa           234        7  1006        37          1
Alaska         523        8   987       949          2
Washington      62        3   849        48          3
Oregon          62        4   973        48          2
Wyoming         73        7  1005       435          1
Louisana        37        8  1099        63          2
Georgia         35        9  1523       345          3

### Paso 13. Selecciona las filas en las que df.deaths es mayor que 50

In [18]:
ejercito.loc[ejercito['deaths'] > 50]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Iowa,Dragoons,1st,234,7,1006,37,1,1,4
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Washington,Dragoons,2nd,62,3,849,48,3,1,31
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3

### Paso 14. Selecciona las filas en las que df.deaths es mayor que 500 o menor que 50

In [19]:
ejercito.loc[(ejercito['deaths'] > 500) | (ejercito['deaths'] < 50)]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Maine,Dragoons,1st,43,4,1592,73,2,0,3
Alaska,Dragoons,2nd,523,8,987,949,2,0,24
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Paso 15. Seleccione todos los regimientos que no se llamen "Dragoons"

In [20]:
ejercito.loc[ejercito['regiment'] != 'Dragoons']

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4
California,Nighthawks,1st,52,42,957,5,2,0,24
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Florida,Nighthawks,2nd,616,2,1400,26,3,1,2
Oregon,Scouts,1st,62,4,973,48,2,0,2
Wyoming,Scouts,1st,73,7,1005,435,1,0,3
Louisana,Scouts,2nd,37,8,1099,63,2,1,2
Georgia,Scouts,2nd,35,9,1523,345,3,1,3

### Paso 16. Selecciona las filas denominadas Texas y Arizona

In [21]:
ejercito.loc[['Texas', 'Arizona']]

,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters
origin,,,,,,,,,
Texas,Nighthawks,2nd,25,2,1099,62,3,1,31
Arizona,Nighthawks,1st,523,5,1045,1,1,1,4

### Paso 17. Selecciona la tercera celda de la fila llamada Arizona

In [25]:
ejercito.loc['Arizona'].iloc[2]

np.int64(523)

### Paso 18. Selecciona la tercera celda en la columna llamada muertes

In [27]:
ejercito['deaths'].iloc[2]

np.int64(25)

In [30]:
ejercito.notnull

<bound method DataFrame.notnull of               regiment company  deaths  battles  size  veterans  readiness  \
origin
Arizona     Nighthawks     1st     523        5  1045         1          1
California  Nighthawks     1st      52       42   957         5          2
Texas       Nighthawks     2nd      25        2  1099        62          3
Florida     Nighthawks     2nd     616        2  1400        26          3
Maine         Dragoons     1st      43        4  1592        73          2
Iowa          Dragoons     1st     234        7  1006        37          1
Alaska        Dragoons     2nd     523        8   987       949          2
Washington    Dragoons     2nd      62        3   849        48          3
Oregon          Scouts     1st      62        4   973        48          2
Wyoming         Scouts     1st      73        7  1005       435          1
Louisana        Scouts     2nd      37        8  1099        63          2
Georgia         Scouts     2nd      35        9  1523       345          3

            armored  deserters
origin
Arizona           1          4
California        0         24
Texas             1         31
Florida           1          2
Maine             0          3
Iowa              1          4
Alaska            0         24
Washington        1         31
Oregon            0          2
Wyoming           0          3
Louisana          1          2
Georgia           1          3  >